version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Dafzal96
    ports:
      - 5432:5432
  
  testing-docker-compose:
    build: 
      context: ./
      dockerfile: Dockerfile
      network: host
    environment:
      - DATABASE_URL=postgresql://postgres:Dafzal96@postgres:5432/docker-compose-db
    ports:
      - 3000:3000
    depends_on:
      - postgres